<?php namespace Modules\Contact\Http\Requests;

use Illuminate\Http\Response;
use Modules\Core\Internationalisation\BaseFormRequest;

class CallRequest extends BaseFormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }
    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        $rules = collect(config('asgard.contact.config.rules'));
        return $rules->except(config('asgard.contact.config.except_rules'))->toArray();
    }

    public function attributes()
    {
        return trans('contact::contacts.form');
    }

    public function messages()
    {
        return trans('validation');
    }

    public function response(array $errors)
    {
        if(\Request::ajax()) {
            return response()->json([
                'success' => false,
                'message' => $errors
            ], Response::HTTP_BAD_REQUEST);
        }
        return parent::response($errors); // TODO: Change the autogenerated stub
    }
}